config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home", to: "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/table", to: "class_details#index"
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_detail.rb
class ClassDetail < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true
  has_many :class_details
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  validates :id, presence: true, length: {is: 8}, uniqueness: true
  validates :name, presence: true

  has_many :courses
  has_many :class_details
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/class_details_controller.rb
class ClassDetailsController < ApplicationController
  def index
    # crawl_data_from_list
    @courses = current_user.courses
    @class_details = current_user.class_details
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_url if logged_in?
  end

  def create
    result = log_in_vnu
    if result.uri.to_s == "#{Settings.base_url}dang-nhap"
      flash.now[:danger] = "Tên người dùng / mật khẩu không chính xác"
      render :new
    elsif result.uri.to_s.eql? Settings.base_url
      flash[:success] = "Đăng nhập thành công !"
      log_in result
      redirect_to root_url
    else
      flash[:danger] = "Đã có sự cố xảy ra."
      redirect_to root_url
    end
  end

  def destroy
    log_out
    flash[:success] = "Bạn đã đăng xuất thành công"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
  include ClassDetailsHelper
end

app/helpers/class_details_helper.rb
module ClassDetailsHelper
  def crawl_data_from_list
    agent = Mechanize.new
    cookies = session[:login_cookies]
    agent.cookie_jar.load StringIO.new(cookies)

    result = agent.get "#{Settings.base_url}xem-va-in-ket-qua-dang-ky-hoc/1?layout=main"
    crawl_courses result
    crawl_class_details result
  end

  private

  def crawl_courses page
    rows = page.search("table")[2].search("tr")
    1.upto(rows.size - 2) do |index|
      strid = rows[index].search("td")[6].text.strip
      course = Course.find_by_strid strid
      if course.nil?
        name = rows[index].search("td")[2].text.strip
        number_of_part = rows[index].search("td")[3].text.strip.to_i
        Course.create strid: strid, name: name, number_of_part: number_of_part,
          student_id: current_user.id
      end
    end
  end

  def crawl_class_details page
    rows = page.search("table")[2].search("tr")
    1.upto(rows.size - 2) do |index|
      strid = rows[index].search("td")[6].text.strip
      course = Course.find_by_strid strid

      # Day of week
      day_of_week = rows[index].search("td")[7].text.strip
      # Thoi gian mon hoc bat dau
      time = get_time rows[index]
      # Thoi luong cua tiet hoc
      duration = get_duration rows[index]
      # Giang duong
      place = get_place rows[index]

      ClassDetail.create! day_of_week: day_of_week[1].to_i, place: place[0],
        class_time: time[0],
        duration: duration[0],
        course_id: course.id, student_id: current_user.id

      # Neu mon hoc hoc trong 2 ngay
      if day_of_week.include? ","
        ClassDetail.create! day_of_week: day_of_week[4].to_i, place: place[1],
          class_time: time[1],
          duration: duration[1],
          course_id: course.id, student_id: current_user.id
      end
    end
  end

  def split_time row
    time = row.search("td")[8].text.strip
    time.gsub!(/\s+/, "")
    split = time.split ","
  end

  def class_in_one_day? row
    time = row.search("td")[8].text.strip
    time.count("-").eql? 1
  end

  def get_time row
    split = split_time row
    return [split[0][0].to_i] if class_in_one_day? row
    [split[0][0].to_i, split[1][0].to_i]
  end

  def get_duration row
    split = split_time row
    duration1 = (split[0][0].to_i - split[0][2..split[0].size].to_i).abs + 1
    return [duration1] if class_in_one_day? row
    duration2 = (split[1][0].to_i - split[1][2..split[1].size].to_i).abs + 1
    [duration1, duration2]
  end

  def get_place row
    str = row.search("td")[9].text.strip
    if !has_two_place? str
      [str]

    # VD: 202T4103T3
    elsif str.count("T").eql?(2)
      [str[0..4], str[5, 10]]

    # VD: Phongmay203T4
    elsif str.include?("Phòng máy") && str.include?("T")

      # Phong may nam sau
      return [str[0..4], "Phòng máy"] if str.index("T").eql? 3
      ["Phòng máy", str[9..(str.size - 1)]]
    end
  end

  def has_two_place? str
    if str.count("T").eql?(2) || (str.include?("Phòng máy") && str.include?("T"))
      return true
    end
    false
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in_vnu
    agent = Mechanize.new
    page = agent.get Settings.base_url
    form = page.forms.first
    form["LoginName"] = params[:session][:student_id]
    form["Password"] = params[:session][:password]
    result = form.submit

    stringio = StringIO.new
    agent.cookie_jar.save(stringio, session: true)
    cookies = stringio.string
    session[:login_cookies] = cookies

    result
  end

  def get_student_name page
    student_info = page.search("span.user-name").text.strip
    student_info[10..40].strip
  end

  def log_in page
    student_id = params[:session][:student_id]
    name = get_student_name page
    student = Student.find_by_id student_id
    student = Student.create id: student_id, name: name if student.nil?
    session[:student_id] = student.id
  end

  def log_out
    session.delete :student_id
  end

  def logged_in?
    session[:student_id].present?
  end

  def current_user
    Student.find_by_id session[:student_id]
  end
end

app/views/class_details/_class_arrange.js.erb
$(document).on('turbolinks:load', function() {
  alert("Loading Complete!");

  <% @class_details.each do |klass| %>
    class_cell = $("#T<%= klass.day_of_week %>-t<%= klass.class_time %>");
    class_cell.html(
      "<h5><%= j klass.course.name %></h5> \
        <p><%= j klass.place %></p> "
    );

    class_cell.attr("colspan", "<%= klass.duration %>");

  <% end %>

  for (let day = 2; day <= 7; day++) {
    for(let time = 1; time <= 10; time++) {
      merge_cell(day, time);
    }
  }

  function merge_cell(day, time) {
    element = $("#T" + day + "-t"+ time);
    colspan = element.attr("colspan");
    for (let index = 1; index < colspan; index++) {
      element = element.next();
      element.hide();
    }
  }

});

app/views/class_details/index.html.erb
<h1>Crawl dữ liệu thành công.</h1>

<h1>Bạn đã đăng kí tổng cộng <%= current_user.courses.count %> môn học</h1>
<table class="table table-bordered" style="table-layout: fixed;">
  <thead>
    <tr>
      <th></th>
      <% 1.upto(10) do |index| %>
        <th><%= index %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% 2.upto(7) do |dow| %>
      <tr>
        <td>Thứ <%= dow %></td>
        <% 1.upto(10) do |time| %>
          <td id="T<%= dow %>-t<%= time %>"></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<script><%= render "class_arrange.js" %></script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
          <li><a href="#">Link</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
              <p class="navbar-text">
                Xin chào, <%= current_user.name %> - <%= current_user.id %>
              </p>
            <%= link_to "Đăng xuất", logout_path, class: "btn btn-danger navbar-btn",
              method: :delete %>
          <% else %>
            <%= link_to "Đăng nhập", login_path, class: "btn btn-default navbar-btn" %>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VnuTimetables</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class = "container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>First landing</h1>
<%= link_to "Generate table", table_path, class: "btn btn-default" if logged_in? %>